// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToBoundary() {
  return window['go']['main']['App']['ConnectToBoundary']();
}

export function ConnectToTarget(arg1) {
  return window['go']['main']['App']['ConnectToTarget'](arg1);
}

export function GetAvailableTargets() {
  return window['go']['main']['App']['GetAvailableTargets']();
}

export function SetupDBeaverConfig(arg1, arg2) {
  return window['go']['main']['App']['SetupDBeaverConfig'](arg1, arg2);
}

export function StoreEnvs(arg1, arg2, arg3) {
  return window['go']['main']['App']['StoreEnvs'](arg1, arg2, arg3);
}

export function ValidateEnv() {
  return window['go']['main']['App']['ValidateEnv']();
}
