// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToTarget(arg1) {
  return window['go']['main']['App']['ConnectToTarget'](arg1);
}

export function GetAvailableTargets() {
  return window['go']['main']['App']['GetAvailableTargets']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SetupDBeaverConfig(arg1, arg2) {
  return window['go']['main']['App']['SetupDBeaverConfig'](arg1, arg2);
}

export function StoreBoundaryAccess(arg1) {
  return window['go']['main']['App']['StoreBoundaryAccess'](arg1);
}

export function StoreDBeaverConfigPath(arg1) {
  return window['go']['main']['App']['StoreDBeaverConfigPath'](arg1);
}
