// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {helpers} from '../models';

export function ConnectToTarget(arg1:string):Promise<helpers.Credentials>;

export function GetAvailableTargets():Promise<Array<helpers.Target>>;

export function Greet(arg1:string):Promise<string>;

export function SetupDBeaverConfig(arg1:helpers.Credentials,arg2:string):Promise<boolean>;

export function StoreBoundaryAccess(arg1:string):Promise<void>;

export function StoreDBeaverConfigPath(arg1:string):Promise<void>;
