// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {helpers} from '../models';

export function ConnectToBoundary():Promise<boolean>;

export function ConnectToTarget(arg1:string):Promise<helpers.Credentials>;

export function GetAvailableTargets():Promise<Array<helpers.Target>>;

export function SetupDBeaverConfig(arg1:helpers.Credentials,arg2:string):Promise<boolean>;

export function StoreEnvs(arg1:string,arg2:string):Promise<boolean>;

export function ValidateEnv():Promise<boolean>;
